- name: Retriving workflow nodes id..
  set_fact:
      workflow_job_nodes_id:  "{{ lookup('ansible.tower.tower_api', 'workflow_jobs/{{workflow_id}}/workflow_nodes', return_ids=True, wantlist=True, return_all=True, max_objects=max_hosts ) }}"
  
- name: Retriving job_ids from workflow_nodes (exclude projects update and utility jobs) ...
  set_fact:
    job_ids: "{{ job_ids | default([]) + [ item_lookup | json_query('summary_fields.job.id')] if item_lookup | json_query('summary_fields.job.id') else [] }}"
  vars:
    item_lookup: "{{ lookup('ansible.tower.tower_api', 'workflow_job_nodes/{{ item }}') }}"
  loop: "{{ workflow_job_nodes_id }}" 

- name: Get host_summaries from the jobs
  set_fact:
    host_summaries: "{{ host_summaries | default([]) +  item_lookup    }}"
  vars:
    item_lookup: "{{ lookup('ansible.tower.tower_api', 'jobs/{{ item }}/job_host_summaries', errors='ignore', wantlist=True, return_all=True, max_objects=max_hosts) }}"
  loop: "{{ job_ids | sort }}"
  when: item

- name: GroupBy hostname in host_summaries
  set_fact:
    host_summaries: "{{ host_summaries | groupby('host_name')  }}"

- name: Fail if host_summaries is empty
  fail:
    msg: "No host_summaries found in jobs of workflow {{ workflow_id }}"
  when: host_summaries | length == 0 or 
        host_summaries is not defined